import { ArrowLeft, Compass } from 'lucide-react';
import { SignIn, SignUp } from '@clerk/react';
import { Link } from 'wouter';

export function AuthPage({ mode, clerkReady }: { mode: 'sign-in' | 'sign-up'; clerkReady: boolean }) {
  const basePath = import.meta.env.BASE_URL.replace(/\/$/, '');
  return <div className="grain flex min-h-[100dvh] items-center justify-center overflow-hidden bg-[#111116] px-4 py-10"><div className="pointer-events-none absolute -left-32 top-1/4 h-96 w-96 rounded-full bg-accent/10 blur-3xl" /><div className="pointer-events-none absolute -right-20 bottom-0 h-96 w-96 rounded-full bg-primary/10 blur-3xl" /><div className="relative w-full max-w-[440px]"><Link href="/" className="mb-7 flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-muted-foreground transition hover:text-primary" data-testid="link-auth-back"><ArrowLeft size={14} /> Return to Animistia</Link>{clerkReady ? <div className="animistia-clerk">{mode === 'sign-in' ? <SignIn routing="path" path={`${basePath}/sign-in`} signUpUrl={`${basePath}/sign-up`} /> : <SignUp routing="path" path={`${basePath}/sign-up`} signInUrl={`${basePath}/sign-in`} />}</div> : <FallbackAuth mode={mode} />}</div></div>;
}

function FallbackAuth({ mode }: { mode: 'sign-in' | 'sign-up' }) {
  return <div className="rounded-2xl border border-white/10 bg-secondary/80 p-7 shadow-2xl backdrop-blur sm:p-9"><div className="mb-8 flex items-center gap-3"><img src="/logo.png" alt="Animistia" className="h-9 w-auto" /><span className="sr-only">Animistia</span></div><div className="mb-7"><div className="mb-2 flex items-center gap-2 font-mono-app text-[10px] uppercase tracking-widest text-primary"><Compass size={13} /> Your private screening room</div><h1 className="font-display text-4xl">{mode === 'sign-in' ? 'Welcome back.' : 'Make yourself at home.'}</h1><p className="mt-2 text-sm text-muted-foreground">Clerk authentication is ready to connect in this environment.</p></div><input placeholder="Email address" className="admin-input mb-3" data-testid="input-auth-email" /><button className="w-full rounded-lg bg-primary py-3 text-xs font-bold uppercase tracking-widest text-primary-foreground" data-testid="button-auth-continue">Continue</button><p className="mt-6 text-center text-xs text-muted-foreground">{mode === 'sign-in' ? <>New here? <Link href="/sign-up" className="text-primary" data-testid="link-auth-sign-up">Create an account</Link></> : <>Already have a space? <Link href="/sign-in" className="text-primary" data-testid="link-auth-sign-in">Sign in</Link></>}</p></div>;
}