import { useEffect, useMemo, useState } from 'react';
import { Filter, Search, SlidersHorizontal, X } from 'lucide-react';
import { useListShows } from '@workspace/api-client-react';
import { ShowCard } from '@/components/ShowCard';
import { LoadingGrid, SectionHeading, Shell } from '@/components/AnimistiaShell';
import { allGenres, demoShows } from '@/lib/catalog';

export default function Browse() {
  const [search, setSearch] = useState('');
  const [genre, setGenre] = useState('');
  const [sourceType, setSourceType] = useState<'uploaded' | 'youtube' | undefined>();
  const [mobileFilters, setMobileFilters] = useState(false);
  const queryParams = useMemo(() => ({ query: search || undefined, genre: genre || undefined, sourceType }), [genre, search, sourceType]);
  const shows = useListShows(queryParams);
  const catalog = shows.data?.length ? shows.data : demoShows;
  const filtered = useMemo(() => catalog.filter((show) => (!search || `${show.title} ${show.synopsis} ${show.genres.join(' ')}`.toLowerCase().includes(search.toLowerCase())) && (!genre || show.genres.includes(genre)) && (!sourceType || show.sourceType === sourceType)), [catalog, genre, search, sourceType]);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === '/' && document.activeElement?.tagName !== 'INPUT') { event.preventDefault(); document.getElementById('catalog-search')?.focus(); } }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, []);
  return <Shell><div className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-12"><div className="animate-rise"><div className="font-mono-app text-[10px] uppercase tracking-[.2em] text-primary">The archive / handpicked titles</div><h1 className="mt-3 max-w-xl font-display text-6xl leading-[.9] tracking-[-.04em] sm:text-8xl">Find your next world.</h1><p className="mt-6 max-w-md text-sm leading-6 text-muted-foreground">A catalog for moods, not algorithms. Search by title, feeling, or the kind of night you want.</p></div>
    <div className="mt-12 flex flex-col gap-3 border-y border-white/[.07] py-4 sm:flex-row"><div className="relative flex-1"><Search size={16} className="absolute left-4 top-1/2 -translate-y-1/2 text-muted-foreground" /><input id="catalog-search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search the archive..." className="h-12 w-full rounded-xl border border-white/10 bg-secondary pl-11 pr-12 text-sm outline-none transition placeholder:text-muted-foreground focus:border-primary/60" data-testid="input-catalog-search" /><kbd className="absolute right-3 top-1/2 hidden -translate-y-1/2 rounded border border-white/10 px-1.5 py-1 font-mono-app text-[10px] text-muted-foreground sm:block">/</kbd>{search && <button onClick={() => setSearch('')} className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground sm:hidden" aria-label="Clear search" data-testid="button-clear-search"><X size={15} /></button>}</div><button onClick={() => setMobileFilters(!mobileFilters)} className="flex h-12 items-center justify-center gap-2 rounded-xl border border-white/10 px-5 text-xs font-bold uppercase tracking-widest text-muted-foreground transition hover:border-primary/50 hover:text-primary sm:hidden" data-testid="button-mobile-filters"><SlidersHorizontal size={15} /> Filters</button><div className={`${mobileFilters ? 'flex' : 'hidden'} flex-col gap-2 sm:flex sm:flex-row`}><FilterSelect label="Genre" value={genre} options={allGenres} onChange={setGenre} testId="select-genre" /><FilterSelect label="Source" value={sourceType ?? ''} options={['uploaded', 'youtube']} onChange={(value) => setSourceType((value as 'uploaded' | 'youtube') || undefined)} testId="select-source" /></div></div>
    <div className="mt-10 flex items-center justify-between"><SectionHeading eyebrow={search || genre ? 'Filtered archive' : 'Browse all'} title={`${filtered.length} ${filtered.length === 1 ? 'title' : 'titles'}`} /><button onClick={() => { setSearch(''); setGenre(''); setSourceType(undefined); }} className="text-xs text-muted-foreground underline-offset-4 hover:text-primary hover:underline" data-testid="button-reset-filters">Reset filters</button></div>
    {shows.isLoading ? <LoadingGrid count={8} /> : shows.isError && !catalog.length ? <div className="rounded-xl border border-destructive/30 p-8 text-sm text-muted-foreground">We could not reach the archive. <button onClick={() => shows.refetch()} className="text-primary" data-testid="button-retry-catalog">Retry connection</button></div> : filtered.length ? <div className="grid grid-cols-2 gap-x-4 gap-y-9 sm:grid-cols-3 lg:grid-cols-4">{filtered.map((show) => <ShowCard key={show.id} show={show} />)}</div> : <div className="flex flex-col items-center rounded-2xl border border-dashed border-white/15 px-6 py-20 text-center"><div className="mb-4 rounded-full border border-primary/30 p-4 text-primary"><Search size={22} /></div><h3 className="font-display text-2xl">Nothing in this constellation.</h3><p className="mt-2 max-w-sm text-sm text-muted-foreground">Try a softer search, another genre, or clear the filters to see everything.</p><button onClick={() => { setSearch(''); setGenre(''); setSourceType(undefined); }} className="mt-5 text-xs font-bold uppercase tracking-widest text-primary" data-testid="button-empty-reset">Clear filters</button></div>}
  </div></Shell>;
}

function FilterSelect({ label, value, options, onChange, testId }: { label: string; value: string; options: string[]; onChange: (value: string) => void; testId: string }) {
  return <label className="flex h-12 items-center gap-2 rounded-xl border border-white/10 bg-secondary px-3 text-[10px] uppercase tracking-widest text-muted-foreground"><span>{label}</span><select value={value} onChange={(e) => onChange(e.target.value)} className="bg-transparent text-xs font-semibold capitalize text-foreground outline-none" data-testid={testId}><option value="">All</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></label>;
}