import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Check, ChevronDown, Clock3, Maximize, Pause, Play, Plus, Share2, Star, Volume2 } from 'lucide-react';
import { Link, useParams } from 'wouter';
import { getGetStorageObjectQueryKey, useGetShow, useGetStorageObject, useListShows } from '@workspace/api-client-react';
import { Shell, LoadingGrid } from '@/components/AnimistiaShell';
import { ShowCard } from '@/components/ShowCard';
import { demoShows, getVideoId } from '@/lib/catalog';

export default function Watch() {
  const params = useParams<{ id: string }>();
  const id = Number(params.id);
  const showQuery = useGetShow(id);
  const all = useListShows();
  const show = showQuery.data ?? demoShows.find((item) => item.id === id) ?? demoShows[0];
  const storagePath = show.videoPath?.replace(/^\/objects\//, '') ?? '';
  const storedVideo = useGetStorageObject(storagePath, { query: { enabled: show.sourceType === 'uploaded' && Boolean(storagePath), queryKey: getGetStorageObjectQueryKey(storagePath) } });
  const [storedVideoUrl, setStoredVideoUrl] = useState('');
  useEffect(() => { if (!storedVideo.data) return; const url = URL.createObjectURL(storedVideo.data); setStoredVideoUrl(url); return () => URL.revokeObjectURL(url); }, [storedVideo.data]);
  const [saved, setSaved] = useState(() => localStorage.getItem(`animistia-saved-${show.id}`) === '1');
  const [playing, setPlaying] = useState(false);
  const related = useMemo(() => (all.data?.length ? all.data : demoShows).filter((item) => item.id !== show.id).slice(0, 4), [all.data, show.id]);
  const save = () => { setSaved(!saved); localStorage.setItem(`animistia-saved-${show.id}`, !saved ? '1' : '0'); };
  if (showQuery.isLoading && !show) return <Shell><div className="mx-auto max-w-[1200px] px-5 py-16"><LoadingGrid count={1} /></div></Shell>;
  return <Shell><div className="mx-auto max-w-[1440px] px-5 py-8 sm:px-8 lg:px-12"><Link href="/browse" className="mb-6 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-muted-foreground transition hover:text-primary" data-testid="link-back-catalog"><ArrowLeft size={14} /> Back to catalog</Link>
    <div className="grid gap-10 lg:grid-cols-[1fr_340px]"><div><div className="relative aspect-video overflow-hidden rounded-2xl border border-white/10 bg-[#0b0b0f] shadow-2xl">
      {show.sourceType === 'youtube' && getVideoId(show.videoUrl) ? <iframe className="h-full w-full" src={`https://www.youtube.com/embed/${getVideoId(show.videoUrl)}?rel=0&modestbranding=1`} title={`${show.title} player`} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen data-testid="iframe-video-player" /> : storedVideoUrl ? <video src={storedVideoUrl} controls className="h-full w-full" data-testid="video-uploaded-player" /> : <div className="relative flex h-full flex-col items-center justify-center overflow-hidden" style={{ background: 'radial-gradient(circle at 50% 38%, rgba(206,157,109,.24), transparent 27%), linear-gradient(135deg,#16151d,#27212d)' }}><div className="absolute h-[130%] w-px rotate-45 bg-primary/20" /><div className="absolute h-[130%] w-px -rotate-45 bg-primary/20" /><button onClick={() => setPlaying(!playing)} className="relative flex h-16 w-16 items-center justify-center rounded-full bg-primary text-primary-foreground transition hover:scale-105" aria-label={playing ? 'Pause preview' : 'Play preview'} data-testid="button-play-preview">{playing ? <Pause size={22} fill="currentColor" /> : <Play size={22} fill="currentColor" />}</button><span className="relative mt-4 font-mono-app text-[10px] uppercase tracking-[.2em] text-white/60">{playing ? 'Preview playing' : 'Ready when you are'}</span></div>}
      <div className="pointer-events-none absolute bottom-0 left-0 right-0 h-20 bg-gradient-to-t from-black/80 to-transparent" /><div className="pointer-events-none absolute bottom-4 left-4 right-4 flex items-center gap-3 text-white"><span className="font-mono-app text-[10px]">00:00</span><div className="h-1 flex-1 rounded-full bg-white/20"><div className="h-1 w-[3%] rounded-full bg-primary" /></div><Volume2 size={15} /><Maximize size={15} /></div>
    </div><div className="mt-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="mb-2 font-mono-app text-[10px] uppercase tracking-[.2em] text-primary">Now watching / Episode 01</div><h1 className="font-display text-4xl leading-tight sm:text-5xl">{show.title}</h1></div><div className="flex gap-2"><button onClick={save} className={`flex items-center gap-2 rounded-full border px-4 py-2 text-xs font-bold uppercase tracking-widest transition ${saved ? 'border-primary bg-primary text-primary-foreground' : 'border-white/15 text-muted-foreground hover:border-primary hover:text-primary'}`} data-testid="button-save-show">{saved ? <Check size={14} /> : <Plus size={14} />}{saved ? 'Saved' : 'My list'}</button><button onClick={() => navigator.clipboard?.writeText(window.location.href)} className="flex h-9 w-9 items-center justify-center rounded-full border border-white/15 text-muted-foreground transition hover:border-primary hover:text-primary" aria-label="Copy show link" data-testid="button-share-show"><Share2 size={14} /></button></div></div>
    <div className="mt-5 flex flex-wrap items-center gap-3 font-mono-app text-[10px] uppercase tracking-widest text-muted-foreground"><span>{show.year}</span><span className="h-1 w-1 rounded-full bg-primary" /><span>{show.episodesCount} episodes</span><span className="h-1 w-1 rounded-full bg-primary" /><span className="flex items-center gap-1 text-primary"><Star size={11} fill="currentColor" />{show.rating.toFixed(1)}</span>{show.genres.map((genre) => <span key={genre} className="rounded border border-white/10 px-2 py-1 normal-case tracking-normal">{genre}</span>)}</div><p className="mt-6 max-w-2xl text-sm leading-7 text-muted-foreground">{show.synopsis}</p>
    </div><aside><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-2xl">More like this</h2><ChevronDown size={17} className="text-primary" /></div><div className="space-y-4">{related.map((item) => <RelatedCard key={item.id} show={item} />)}</div><div className="mt-7 rounded-xl border border-white/10 bg-secondary/60 p-4"><div className="flex items-center gap-2 font-mono-app text-[10px] uppercase tracking-widest text-primary"><Clock3 size={13} /> A good evening</div><p className="mt-3 text-xs leading-5 text-muted-foreground">No rush. Let the next story find its own pace.</p></div></aside></div>
  </div></Shell>;
}

function RelatedCard({ show }: { show: import('@workspace/api-client-react').Show }) {
  return <Link href={`/watch/${show.id}`} className="group flex gap-3" data-testid={`link-related-${show.id}`}><div className="relative h-20 w-28 shrink-0 overflow-hidden rounded-lg" style={{ background: 'linear-gradient(135deg,#252035,#bd796d)' }}><span className="absolute bottom-2 left-2 font-display text-2xl text-white/75">{show.title.slice(0, 1)}</span><div className="absolute inset-0 bg-black/10 transition group-hover:bg-transparent" /></div><div className="min-w-0 py-1"><h3 className="truncate text-sm font-semibold text-foreground transition group-hover:text-primary">{show.title}</h3><p className="mt-1 line-clamp-2 text-xs leading-4 text-muted-foreground">{show.genres.join(' · ')} / {show.year}</p></div></Link>;
}